### ISSUE TITLE
Is contrast currently broken? 

### ISSUE THREAD

**Issue by ratatoeskr666** [johannesjo/angular-material-css-vars#115]
### :speaking_head: Foreword

Should the contrast option change the font colors for primary, accent, warn palette colors? 
Seems to be broken with Angular 15 and in the demo: 
https://johannesjo.github.io/angular-material-css-vars/

## :ghost: Brief Description

Toggle the contrast option(s) has no impact on the visual result

## :pancakes: Action version

Latest version: v4.0.2

**Comment by ratatoeskr666** [comment]
Looks like the new mdc components of material v15 uses own variables like `--mdc-protected-button-label-text-color` which are being set in those default palette files _(deeppurple-amber.css, indigo-pink.css, ...)_

**Comment by json-derulo** [comment]
Version 5.0.0-next.0 was just released, which fixes the issue. Please note that stable v5 will also contain the update to Angular 16.

**Comment by json-derulo** [comment]
It doesn't seem to be fixed... will have a look again soon, sorry for the confusion
