### ISSUE TITLE
How to use it with Angular 14

### ISSUE THREAD

**Issue by Wlada** [johannesjo/angular-material-css-vars#118]
How to use it with angular 14 since latest version has deps ?

`  "peerDependencies": {
    "@angular/common": ">=15",
    "@angular/core": ">=15",
    "@angular/material": ">=15"
  },`
  
  If not this version, which version is for angular 14?
  
  Also, after an upgrade to angular 14 I'm having an issue with @use import.

  `@use 'angular-material-css-vars/main' as mat-css;`
  
  can't find main to import/use

**Comment by johannesjo** [comment]
To use it with angular 14 use version `3.0.0`.

**Comment by Wlada** [comment]
I don't see a tag 3.0.0. When I put it in package.json, it will install 2.1.2.

I was sure that it was a 3.0.0 tag before.

**Comment by Wlada** [comment]
Import issue is present as described in this task  
https://github.com/johannesjo/angular-material-css-vars/issues/94

But with 3.0.0, I probably won't have a problem with import, but as I said, that version tag is not present anymore.

**Comment by Wlada** [comment]
@johannesjo  I managed to install version 3.0.0, but the import issue is still present. 

<img width="684" alt="Screenshot 2023-02-01 at 12 09 05" src="https://user-images.githubusercontent.com/1298077/216026724-14235186-aba1-49ec-ac4a-f297d9c2f1c8.png">

Any idea why? I can see package.json export syntax is not working.

**Comment by Wlada** [comment]
problem resolved with this import

@import '~angular-material-css-vars/src/lib/_main.scss';

**Comment by Wlada** [comment]
Thanks for your help
