### ISSUE TITLE
Error unless public-util imported

### ISSUE THREAD

**Issue by cgatian** [johannesjo/angular-material-css-vars#12]
I receive the following error with a brand new Angular CLI app:

```bash
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $string: null is not a string.
```

If I import the public-utils in the `styles.scss` it seems to compile

**Comment by johannesjo** [comment]
Thanks for the hint. I'll check this asap.

**Comment by johannesjo** [comment]
Should be fixed with the new release.

**Comment by cgatian** [comment]
Wow thanks for the quick turnaround! 🎊

**Comment by cgatian** [comment]
@johannesjo I think you published the root of the repo, not a build of the project dist.

**Comment by johannesjo** [comment]
You're right. I thought I had this completely automated, but not quite :)

**Comment by cgatian** [comment]
0.1.9 is published with the project root, not dist.
![image](https://user-images.githubusercontent.com/1752170/72261286-86e11380-35e2-11ea-9755-1339e0406590.png)

**Comment by cgatian** [comment]
@johannesjo See above please. 0.1.9 is still incorrect
