### ISSUE TITLE
Docs on $mat-css-dark-theme-selector and $mat-css-light-theme-selector not accurate

### ISSUE THREAD

**Issue by dflor003** [johannesjo/angular-material-css-vars#122]
## :ghost: Brief Description

It seems that the docs around `$mat-css-dark-theme-selector` and `$mat-css-light-theme-selector` are no longer accurate. I just upgraded from `1.1.1` to `4.2.1` and most of the css var overrides were not working.

After banging my head against the keyboard for a few hours and digging into the code, I found that doing the following no longer works:

```scss
$mat-css-dark-theme-selector: '.isDarkTheme';
$mat-css-light-theme-selector: '.isLightTheme';
```

I was able to restore the behavior by doing this:

```scss
$mat-css-dark-theme-selector: '.theme-dark';

@include mat-css.init-material-css-vars(
  $dark-theme-selector: $mat-css-dark-theme-selector
);
```

However, I wasn't able to find where to pass the light theme selector. Is that no longer supported? In either case, it would be good to update the docs to reflect whatever the new pattern should be for that.

## :pancakes: Action version

4.2.1

## Steps To Reproduce

1. Follow the docs from `README.md`

## :police_car: Expected behavior

You can successfully setup angular-material-css-vars

**Comment by mruknowme** [comment]
Thank you @dflor003 for the solution , I was wondering why dark mode suddenly stopped working

**Comment by json-derulo** [comment]
Those variables were renamed, see https://github.com/johannesjo/angular-material-css-vars/pull/114#issuecomment-1399968857. It looks like some parts of the documentation were missed to update.

**Comment by json-derulo** [comment]
Thanks for bringing this up, docs are updated now. Will also mark this as a breaking change of v5 (even though this change happened in v4).
