### ISSUE TITLE
Legacy Checkbox - checkmark not displayed anymore

### ISSUE THREAD

**Issue by dkimmich-onventis** [johannesjo/angular-material-css-vars#124]
## :ghost: Brief Description

The check icon of the legacy checkbox is not displayed anymore.

![image](https://user-images.githubusercontent.com/68286501/218688165-79c166a5-f868-4395-9f2c-da43ef4baed6.png)

## :pancakes: Action version

Until v4.2.1 it works fine, since v4.2.2 it's broken.

## Steps To Reproduce

1. Use `$load-legacy-components: true` setting
2. Add a legacy checkbox to your application
3. Check the checkbox

## :police_car: Expected behavior

The check icon is displayed.

![image](https://user-images.githubusercontent.com/68286501/218687957-58096636-5b69-4658-a8fd-b20ab4adbbcd.png)

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by johannesjo** [comment]
Thanks for reporting! PRs are welcome!
