### ISSUE TITLE
Material 15: Usage of default palettes

### ISSUE THREAD

**Issue by leomayer** [johannesjo/angular-material-css-vars#125]
## :ghost: Brief Description

I've now installed the new version. I'm using Angular Material 15 and we use some of the default palettes, e.g.

```
$primary-color: mat.get-color-from-palette($lightIndigo, 500);
```

I use the `$lightIndigo` as a definition of a name for a palette. The error occurs on `$mat-indigo`.

## :pancakes: Version from the `package.json`

```
angular-material-css-vars": "^4.2.2",
```

## :tophat: workflow configuration

```
@use '@angular/material' as mat;
@use 'angular-material-css-vars/main' as mat-css;

// optional
$mat-css-dark-theme-selector: '.isDarkTheme';
$mat-css-light-theme-selector: '.isLightTheme';

// init theme
@include mat-css.init-material-css-vars() using($mat-css-theme) {
	// If your app has any theme mixins, call them here.
	// $mat-css-theme gets set to an appropriate value before this content is called.
	// @include your-custom-component-theme($mat-css-theme);
}

$primaryPalette: mat-palette($mat-indigo);
```

results in a compile error

```
./src/styles_for_table.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
   ╷
22 │ $primaryPalette: mat-palette($mat-indigo);
   │                              ^^^^^^^^^^^
   ╵
  src/styles_angular_material.scss 22:30  @import


```
 Don't know if the naming is a coincidence or if there are some reserved words. Anyway it cannot compile.

**Comment by json-derulo** [comment]
What is `$mat-indigo`? It's neither a variable defined by `@angular/material`, nor by this package, also it's not part of the code you posted. It could be that in a previous major version of Angular Material this variable existed but was removed in the meantime.

Can you try using `mat.$indigo-palette` instead? See the [Angular Material Theming Docs](https://material.angular.io/guide/theming#predefined-palettes).

**Comment by json-derulo** [comment]
Angular Material's `@angular/material/theming` Sass entrypoint exports the variable `$mat-indigo`. But you seem to use the new entrypoint `@angular/material`, where the exported variables are not anymore prefixed with `mat-`. Can you try `mat.$indigo-palette` or `mat.$indigo` instead?

**Comment by leomayer** [comment]
Using `mat.$indigo-palette` seems to work. At least I don't get more errors.

Just out of curiosity: Where to find the name of the palettes?

**Comment by json-derulo** [comment]
@leomayer Great to hear that it works.

According to the [docs](https://material.angular.io/guide/theming#predefined-palettes), a full list of the predefined palettes can be found in the [Material Design v1 docs](https://m1.material.io/style/color.html#color-color-palette). Unfortunately the docs don't contain a full list of predefined palettes you can use, but you can find this in their code:

https://github.com/angular/components/blob/d4213d5bdbb486a70e517b87895a53e8ec03fe78/src/material/_index.scss#L6-L11
