### ISSUE TITLE
Foreground and Background mapping

### ISSUE THREAD

**Issue by jaetea** [johannesjo/angular-material-css-vars#128]
I don't see anything in the documentation to do this in a custom component but maybe I'm missing something. I'm simple trying to set a variable to a foreground mapped value

`$mat-option-hover-background: mat-color($foreground, base, 0.07);`

I'm just getting an undefined variable error. It could be because I'm trying to set these variables before I call init-material-css-vars but I can't call it after because the material theme files are looking for this value.

This works 

`$mat-option-hover-background: map-get($mat-css-default-light-theme, --palette-foreground-base);`

but the issue is I'm explicity setting it to the light-theme which I don't want to do as the user can pick light or dark theme.

**Comment by json-derulo** [comment]
As a workaround, you can set the colors for the light and dark mode separately, using the `.isDarkTheme` selector (or custom selector, if applicable):

```
mat-option {
  background-color: map-get($mat-css-default-light-theme, --palette-foreground-base);
} 

.isDarkTheme :host mat-option {
   background-color: map-get($mat-css-default-dark-theme, --palette-foreground-base);
}
```

I will try to find a better solution using a single variable only, will let you know about the result.

**Comment by jaetea** [comment]
no longer needed.
