### ISSUE TITLE
rgba missing?

### ISSUE THREAD

**Issue by cgatian** [johannesjo/angular-material-css-vars#13]
My vars show up but they are missing rgba in front of them?
![image](https://user-images.githubusercontent.com/1752170/72187031-97b43e00-33c4-11ea-9c69-84044537bb43.png)

**Comment by johannesjo** [comment]
@cgatian thanks for reporting. Haven't encountered this for myself. What version of sass are you using?

**Comment by cgatian** [comment]
Hmm whatever the latest Angular CLI has. Looks like 1.23.3?

**Comment by cgatian** [comment]
Using mixins like `mat-css-color-and-contrast` and `mat-css-color-primary` output with rgb

**Comment by johannesjo** [comment]
This happens only for the mixins? Or does this happen for every angular material component?

**Comment by cgatian** [comment]
Hmm maybe it's due to using @angular/material@next. Will try 8

**Comment by cgatian** [comment]
Yeah @angular/material-8.2.3 is working. Must be a change with 9.0.0-rc.8

**Comment by cgatian** [comment]
Hmm Ill double check my project. Looking through the changes on Material I dont see anything that would cause a breaking change.

**Comment by cgatian** [comment]
Error I get in a fresh Angular 9 CLI project
![image](https://user-images.githubusercontent.com/1752170/72286373-0b4b8a80-3613-11ea-9ab8-44b9b400075c.png)

**Comment by cgatian** [comment]
When I structure the imports like this
```scss
@import '~angular-material-css-vars/main';
@import '~angular-material-css-vars/public-util';
```
The error goes away, but rgb is not shown in the compiled css

**Comment by johannesjo** [comment]
Thanks for investigating. Not sure if it makes sense to make adjustments before the stable versions are out. If you want to debug further however, you can use the debug statement of sass inside the function where the error is thrown, like so:
```
// main overwrite to make it all work
@function mat-color($palette, $hue: default, $opacity: null) {
  @if type-of($hue) == number and $hue >= 0 and $hue <= 1 {
    @return mat-color($palette, default, $hue);
  }

  $color: map-get($palette, $hue);
   // color is null for the error, so it would be interesting to know why
   @debug $palette;
   @debug $hue;
   // current context would be good to know too
   @debug &;


  @if type-of($color) == color {
    @return rgba($color, if($opacity == null, opacity($color), $opacity));
  } @else {
    $default-opacity: if($opacity == null, 1, $opacity);
    $inner-var-alpha-str: str-slice($color, 5, -2) + '-alpha';
    // if we have a corresponding alpha variable use it
    @if (map_get($mat-css-default-light-theme, $inner-var-alpha-str)) {
      @return rgba($color, _mat-css-str-replace($color, ')', "-alpha, #{$default-opacity})"));
    } @else {
      @return rgba($color, $default-opacity);
    }
  }
}
```

**Comment by johannesjo** [comment]
Also: To me it looks like importing this after the main stuff, just (silently) breaks the necessary overwrite for some reason:
``` 
@import '~angular-material-css-vars/public-util';
```

Never made any experiments with that but maybe the first overwrite of the function is ignored when a second overwrite is made. Not sure though

**Comment by cgatian** [comment]
@johannesjo determined the issue. It looks like Angular added an additional type to the background palette to theme the tooltip. PR coming.

https://github.com/angular/components/pull/17643

Thoughts on maybe making a "next" branch to add Angular Material 9.0 changes to? Otherwise we should hold off on merging until shes released.

Also, thanks for the debugging tip BTW, had no idea you could do that with SCSS.

**Comment by johannesjo** [comment]
@cgatian I gladly add a next branch if we happen to need it for a specific fix, that would break angular 8.
