### ISSUE TITLE
nit: mat-css-color-and-contrast name

### ISSUE THREAD

**Issue by cgatian** [johannesjo/angular-material-css-vars#14]
When I first used `mat-css-color-and-contrast` I assumed it might take a secondary property for the palette (e.g. warn, accent). Looking at the code there's mixins for each. 

To follow with the existing naming convention it might be nice if primary was added.
`mat-css-color-and-contrast` => `mat-css-color-and-contrast-primary`

**Comment by cgatian** [comment]
BTW this is amazing. Thank you for your work!

**Comment by johannesjo** [comment]
Glad that you like it. Makes a lot of sense, what you're saying. Would you by any chance be willing to provide a pull request for that?
