### ISSUE TITLE
tinycolor2 dependency missing in package.json

### ISSUE THREAD

**Issue by cgatian** [johannesjo/angular-material-css-vars#15]
tinycolor2 needs to be added as a dev dependency to the root project's `package.json` in order to run a `npm run lib.build`

**Comment by johannesjo** [comment]
Not sure what the best way to handle this is. `tinycolor2` is not a dependency of the demo project. It is located inside `projects/material-css-vars/package.json`.

**Comment by cgatian** [comment]
@johannesjo I think if you do an `npm ci` on your machine then try running `npm run lib.build` you will see the issue. 
It's properly defined as a dependency of the distributed package, but its not in the root package.json

**Comment by johannesjo** [comment]
Tinycolor is a dependency of the lib not of the demo. IMHO it doesn't make much sense to add it to the main package.json. the error message is also very clear in reminding you to install the dependencies for the lib. Adding it to the main package json as another dep might lead to a different version being used for development and the packed and published lib, which is not what we want.

**Comment by cgatian** [comment]
I found this error because I was trying to build the library.

I cloned
Ran npm install
Ran npm build
Error occurred

I guess I think it's strange that this process doesn't work, especially if there was a CI in place.
