### ISSUE TITLE
Bug: Material Button background color broken on mouse down after the newest angular update 

### ISSUE THREAD

**Issue by kindy91** [johannesjo/angular-material-css-vars#161]
## :ghost: Brief Description

The background color of a button becomes the same as the text on mousedown, for example in primary color buttons, leaving the whole button to either be fully white or black until mouseup occurs. This occured to me after updating to angular `17.2.4` while working on mat-css-vars `6.1.1`

## Reproduction

StackBlitz / reproduction repository link: https://stackblitz.com/~/github.com/kindy91/mat-css-vars-project

1. Click the button and keep on clicking it
2. You will notice the background of the button becomes the same as the text and the whole button will be white.
3. Stop clicking, the button will return back to normal.

## :police_car: Expected behavior

On mousedown, the button should have the normal mousedown color change behavior but not have the background be the same color as the button text.

**Comment by json-derulo** [comment]
Thanks for opening the issue. In the past similar issues occurred when Angular changed the names of their CSS variables. I am on vacation for 1 more week and can have a look afterwards. If someone wants to work on this, I will be accepting PRs.

**Comment by mpo-dev** [comment]
I've also ran into the same issue, seems to be introduced in Angular Material 17.2.2. For the time being you could downgrade to the last supported version:
```
npm i @angular/cdk@17.2.1 @angular/material@17.2.1
```

**Comment by json-derulo** [comment]
Did anyone check whether the issue is still present with Angular Material v17.3.0?

**Comment by kindy91** [comment]
Yes it still proceeds with the new minor update

**Comment by json-derulo** [comment]
> Yes it still proceeds with the new minor update

This doesn't seem to be the case. After updating to Angular Material v17.3.0 in the given StackBlitz, the issue is gone. Also I could reproduce the issue in the demo application of this repository, but only with Angular Material v17.2.2.

**Comment by kindy91** [comment]
must have been a cache problem. I am using version `v.17.3.1` and works fine
