### ISSUE TITLE
Angular testing:  No provider for InjectionToken Mat Css Config

### ISSUE THREAD

**Issue by thaissarojas** [johannesjo/angular-material-css-vars#18]
For testing i'm using karma and jasmine, and i'm using the MaterialCssVarsService on the `app.component.ts.` When i run ng test i get this error:

> NullInjectorError: StaticInjectorError(DynamicTestModule)[MaterialCssVarsService -> InjectionToken Mat Css Config]: 
  StaticInjectorError(Platform: core)[MaterialCssVarsService -> InjectionToken Mat Css Config]: 
    NullInjectorError: No provider for InjectionToken Mat Css Config!
NullInjectorError: StaticInjectorError(DynamicTestModule)[MaterialCssVarsService -> InjectionToken Mat Css Config]: 
  StaticInjectorError(Platform: core)[MaterialCssVarsService -> InjectionToken Mat Css Config]: 
    NullInjectorError: No provider for InjectionToken Mat Css Config!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:725:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11918:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11862:1)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11764:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11918:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11862:1)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:11764:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:20234:1)
    at _createClass (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:20281:1)
    at _createProviderInstance (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm5/core.js:20251:1)

I've already added MaterialCssVarsService to the providers but i keep getting this error. What should I do? What is this mat css config?

**Comment by johannesjo** [comment]
Which version of angular are you using?

**Comment by thaissarojas** [comment]
I'm using angular 8

**Comment by johannesjo** [comment]
There is probably something wrong in the way you're importing the module. Could you please share, how you the lib is setup in your project?

**Comment by thaissarojas** [comment]
the error only shows when i run ngtest
so i imported it to the .spec file as:
```  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ 
        ThemeComponent,
      ],
      imports: [
        SharedModule,
        ColorPickerModule,
        MaterialFileInputModule
      ]
    })
    .compileComponents();
  }
```
but i set up the project exaclty as the tutorial says

**Comment by johannesjo** [comment]
Not sure. Haven't encountered any issues with testing so far, but this might help:
```  beforeEach(async(() => {
    TestBed.configureTestingModule({
        // ...
         providers: [{
          provide: MATERIAL_CSS_VARS_CFG, useValue: ---custom cfg---
        }]
    })
    .compileComponents();
  }
```

Not sure why this might be necessary, but I doubt that it is a special issue with this library.

Also maybe this helps:
https://stackoverflow.com/questions/52607342/angular-testing-mocking-an-injectiontoken

**Comment by thaissarojas** [comment]
but what is this custom cfg??

**Comment by johannesjo** [comment]
It's the configuration for this library. Looks like this: https://github.com/johannesjo/angular-material-css-vars/blob/master/projects/material-css-vars/src/lib/default-cfg.const.ts

**Comment by mscard02** [comment]
i am facing the same issue.  I tried the above-posted code and also tried implementing a very basic version of useValue and no use value.  No luck.

**Comment by johannesjo** [comment]
I need more information, as I am unable to reproduce this. How do the tests look like? How does the component in question look like? How are service and module included? Does the error occur only for a particular setup or always?

**Comment by mscard02** [comment]
here is a brand new generated angular app I created with just angular material and your npm package installed so that you can easily see the issue.   just run ng test and you can see the error message.

https://github.com/mscard02/dynamic-color-issue

**Comment by thaissarojas** [comment]
any updates?

**Comment by johannesjo** [comment]
I think the "right" approach in terms of straight unit testing would be to mock out the service (and all other external depdencies) rather than the config like so::
```
      providers: [{
        provide: MaterialCssVarsService,
        useClass: class {
          setDarkTheme = jasmine.createSpy('setDarkTheme');
          setPrimaryColor = jasmine.createSpy('setPrimaryColor');
          setAccentColor = jasmine.createSpy('setAccentColor');
          // ...
        }
      }]
```

Not sure why the config throws an error otherwise. Help of someone with more insight into the whole testing setup with angular would be very welcome!

**Comment by danipj** [comment]
Had the same issue, solved it by including MaterialCssVarsModule.forRoot() on my imports array
