### ISSUE TITLE
mat-ripple background-color bug

### ISSUE THREAD

**Issue by pedrojrivera** [johannesjo/angular-material-css-vars#19]
We discovered that the mat-ripple background color on light theme is not displaying correctly.
We discovered the following in the generated styles:

```
.mat-checkbox .mat-ripple-element {
    background-color: var(--palette-foreground-base);
}
```
We had to override the style to include the rgb() function.
```
.isLightTheme .mat-checkbox .mat-ripple-element {
  background-color: rgb(var(--palette-foreground-base));
}
```

**Comment by johannesjo** [comment]
Thanks for sharing. I'll check if there is another way to fix this.

**Comment by johannesjo** [comment]
Seems like this will be added  with this:
https://github.com/johannesjo/angular-material-css-vars/pull/21

**Comment by gotwig** [comment]
is this still open?

**Comment by johannesjo** [comment]
No... :-D
