### ISSUE TITLE
New color algorithm and bug fixes

### ISSUE THREAD

**Issue by pedrojrivera** [johannesjo/angular-material-css-vars#20]
I forked your code and added a new color algorithm and fixed a bunch of bugs that we found when we were implementing it in our existing project. You can see our changes here:

https://github.com/pedrojrivera/angular-material-css-vars/tree/feature/googlePaletteColors

Thanks!

**Comment by johannesjo** [comment]
Thanks for sharing! This looks promising and probably should be the default behavior (not sure if we even need the old method...). Would you be willing to provide a PR for the changes? That would be great! Be warned though that I recently (a couple of hours ago) migrated everything from angular 8 to 9.

**Comment by pedrojrivera** [comment]
@johannesjo I'll generate a PR.  Thanks!

**Comment by gotwig** [comment]
what happened to the PR? is this still open?

**Comment by johannesjo** [comment]
https://github.com/johannesjo/angular-material-css-vars/pull/21

I just forgot to close this issue :)
