### ISSUE TITLE
Compatibility with angular 7.x 

### ISSUE THREAD

**Issue by hmobs** [johannesjo/angular-material-css-vars#23]
Hi. I'm getting the following error:

`ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

      background: mix($app-background, rgba($badge-color, 1), (1 - $badge-opacity) * 100%);
                                      ^
      Argument `$color` of `rgba($color, $alpha)` must be a color
      in /Users/git/project/node_modules/@angular/material/_theming.scss (line 1899, column 40)`

I have a feeling it has to do with my angular/angular material version (7.2) - I've tried using an earlier version of the library (0.2.1) and still had no luck. Am I correct in my assumption? Any ideas?

Thanks!

**Comment by johannesjo** [comment]
Hey there! You're probably right with your guess.  Currently there is no support for angular 7 though I imagine that making it work should definitely be possible.

**Comment by hmobs** [comment]
After a surprisingly painless update to Angular 8, everything seems to be working. Thanks a bunch.

**Comment by johannesjo** [comment]
That's great to hear! :) Glad you made it work!
