### ISSUE TITLE
Issue when building for production with AOT compiler

### ISSUE THREAD

**Issue by mscard02** [johannesjo/angular-material-css-vars#24]
I have followed the instructions as linked on the readme, and all works wonderfully in development with ng serve.  However, when ng serve --prod is running I receive an error saying, "StaticInjectorError(AppModule)[DynamicColorsModule -> MaterialCssVarsService_1]: 
  StaticInjectorError(Platform: core)[DynamicColorsModule -> MaterialCssVarsService_1]: 
    NullInjectorError: No provider for MaterialCssVarsService_1!"

I am using Angular 8

**Comment by johannesjo** [comment]
I am unable to reproduce this neither with angular 8 or 9.

**Comment by mscard02** [comment]
here is a brand new generated angular app I created with just angular material and your npm package installed so that you can easily see the issue.  it will run fine with just ng serve, but run ng serve --prod and you will see the error with aot compilation kicks in.  this replicates what we are seeing on our servers.

https://github.com/mscard02/dynamic-color-issue

**Comment by johannesjo** [comment]
hmhm still no error with
```
ng serve --prod --aot
```
Neither with
```
ng build --prod --aot
```
Which OS are you on?

**Comment by mscard02** [comment]
i am on windows 10 using VSCode as my code editor.  The same happened to me on both my work laptop and home pc.  When I mention an error, it builds correctly, but the error will show in the chrome console.   I appreciate the quick responses!

![image](https://user-images.githubusercontent.com/1520571/75589671-644b7280-5a49-11ea-833e-e2ac47c1b969.png)

**Comment by mscard02** [comment]
I also found that setting the aot and build optimizer to false (build optimizer has to be false with aot turned off)  will fix the problem and it will display in the browser with no issues.

![image](https://user-images.githubusercontent.com/1520571/75589998-4d595000-5a4a-11ea-9756-2d53a6bdcef9.png)

**Comment by johannesjo** [comment]
Not really sure why that is the case. As a temporary workaround you can use:
```
  providers: [MaterialCssVarsService],
``` 
inside app.module.ts

**Comment by johannesjo** [comment]
Generally speaking: I doubt that this an issue of angular-material-css and rather some build weirdness going on with angular with specific versions. The service is `  providedIn: 'root' ` might be that this doesn't work so well with libraries under some circumstances. I really don't know.
