### ISSUE TITLE
initMatTheme does not allow for other mixins to be called with themes

### ISSUE THREAD

**Issue by literalpie** [johannesjo/angular-material-css-vars#26]
It is not uncommon for applications to have multiple theme mixins, following [this guide](https://material.angular.io/guide/theming-your-components). Currently, this library doesn't allow you to access the theme generated and pass it into your own mixins.

One way to handle this would be to use the @content feature of sass similar to what's suggested in [this stackoverflow](https://stackoverflow.com/a/51479175/7151388) and what [Material does for MDC mixins](https://github.com/angular/components/blob/dbb0b23402f63216bcf2fce20205333ccbacb751/src/material-experimental/mdc-helpers/_mdc-helpers.scss#L116).

I'm thinking it would look something like:
```
initMatTheme(){
    // $theme gets created by the mixin so we can use it here
    // content we pass in this block will get applied  both at the root and within the dark theme selector
    my-mixin($theme);
}
```

Let me know if you think it's a good idea. I may be able to contribute.

**Comment by johannesjo** [comment]
Thanks for opening this up! Never used this approach to be honest. Could you maybe outline an example how you would think this should work?
