### ISSUE TITLE
Fix mat-color overwrite opacity

### ISSUE THREAD

**Issue by picc09** [johannesjo/angular-material-css-vars#3]
Thank you for your great work, I adopted it and I found a small bug.

Sometimes when Material applies colors (primary, accent or warn) sets the opacity value.
You can check this behavior with SlideToggle, when checked the class **.mat-slide-toggle-bar** uses _accent-500_ with 0.54 of opacity.

To fix the problem, when your version of **mat-color** returns the variable:

`@return rgba($color, _mat-css-str-replace($color, ')', '-alpha, 1'));`

I replaced the default value with the Material expected value:

`$default-opacity: if($opacity == null, 1, $opacity);`
`@return rgba($color, _mat-css-str-replace($color, ')', "-alpha, #{$default-opacity})"));`

Nothing more and this seems to solve all the problems I've found.
I hope this will help you.

**Comment by johannesjo** [comment]
Thank you very much! That's a great catch! I'll make a patch release in a bit.
