### ISSUE TITLE
no mixin named app-theme

### ISSUE THREAD

**Issue by zithith** [johannesjo/angular-material-css-vars#34]
Hi there,
After installing and adding the code as per the documentation page, I tried building the app to make sure the base framework was good before implementing the themes in the components.
Initially I was hit by a Null Injector issue, but it seems that adding "postinstall": "ngcc" and doing an npm install has rid me of this, but I am still seeing an issue where the compiler complains that the mixin app-theme doesn't exist.
Checking the repo I can see it does exist here, but in the node_module compiled library on my machine I can't find it.

**Comment by johannesjo** [comment]
Hey there! This is a missing update in the readme. Thanks for reporting.

It should be `init-material-css-vars`now instead.

**Comment by johannesjo** [comment]
Thanks for reporting. The readme was a little misleading on this part. I fixed it.
