### ISSUE TITLE
Disabled mat-select not colored grey by default

### ISSUE THREAD

**Issue by astone2014** [johannesjo/angular-material-css-vars#35]
The mat select options that are listed as disabled are not grayed out.
https://i.imgur.com/otDUWoQ.png
https://i.imgur.com/CuqiseH.png

rendered css variables
.mat-option.mat-option-disabled {
    color: rgba(var(--palette-foreground-hint-text), 1);
}

in scss
&.mat-option-disabled {
    color: mat-color($foreground, hint-text);
}

Why is the mat-color($foreground, hint-text) = rgb(0, 0, 0)?
I don't think I modified the foreground color. Do I need to set it?

**Comment by johannesjo** [comment]
Thanks for opening this up. Good question. Don't have the answer unfortunately.  There might be definitely some minor (as far as I can see very very few) quirks left, one needs to address manually. Have a look here: 
https://github.com/johannesjo/angular-material-css-vars/blob/ac0725454429d1e827a96397bcba845091499821/projects/material-css-vars/src/lib/_mat-lib-overwrites.scss#L43-L50

Could you maybe dig into it for the rest of us? This would be very much appreciated!

**Comment by astone2014** [comment]
> Could you maybe dig into it for the rest of us? This would be very much appreciated!
Most definitely. I'll open a merge request when I've got it figured out.

**Comment by johannesjo** [comment]
That's awesome! Thank you!

**Comment by astone2014** [comment]
https://github.com/johannesjo/angular-material-css-vars/blob/ac0725454429d1e827a96397bcba845091499821/projects/material-css-vars/src/lib/_variables.scss#L133

We are using
```$dark-disabled-text: rgba(black, 0.38);```
When in light mode we should use:
```$light-disabled-text: rgba(white, 0.5);```

Looks like we set the foreground once in main.scss
https://github.com/johannesjo/angular-material-css-vars/blob/ac0725454429d1e827a96397bcba845091499821/projects/material-css-vars/src/lib/_main.scss#L25-L30

We only have a single foreground palette for both dark and light theme.
https://github.com/johannesjo/angular-material-css-vars/blob/ac0725454429d1e827a96397bcba845091499821/projects/material-css-vars/src/lib/_variables.scss#L273-L289

We decided to use dark variables for all the foreground so the disabled color works in dark mode but not in light mode. We need to switch between two colored pallets like in angular material.
```
// Foreground palette for light themes.
$mat-light-theme-foreground: (
  base:              black,
  divider:           $dark-dividers,
  dividers:          $dark-dividers,
  disabled:          $dark-disabled-text,
  disabled-button:   rgba(black, 0.26),
  disabled-text:     $dark-disabled-text,
  elevation:         black,
  hint-text:         $dark-disabled-text,
  secondary-text:    $dark-secondary-text,
  icon:              rgba(black, 0.54),
  icons:             rgba(black, 0.54),
  text:              rgba(black, 0.87),
  slider-min:        rgba(black, 0.87),
  slider-off:        rgba(black, 0.26),
  slider-off-active: rgba(black, 0.38),
);

// Foreground palette for dark themes.
$mat-dark-theme-foreground: (
  base:              white,
  divider:           $light-dividers,
  dividers:          $light-dividers,
  disabled:          $light-disabled-text,
  disabled-button:   rgba(white, 0.3),
  disabled-text:     $light-disabled-text,
  elevation:         black,
  hint-text:         $light-disabled-text,
  secondary-text:    $light-secondary-text,
  icon:              white,
  icons:             white,
  text:              white,
  slider-min:        white,
  slider-off:        rgba(white, 0.3),
  slider-off-active: rgba(white, 0.3),
);
```
https://github.com/angular/material-builds/blob/ff400ae4c133deebc510c7a75f468c7c1ee9feab/_theming.scss#L1257-L1293

I'm not great at scss yet but I think we need to create another set of

**Comment by johannesjo** [comment]
> I'm not great at scss yet but I think we need to create another set of

of what? :)

Not sure if I follow you. The selectors for the dark theme is applied here:
https://github.com/johannesjo/angular-material-css-vars/blob/ac0725454429d1e827a96397bcba845091499821/projects/material-css-vars/src/lib/_main.scss#L32-L46

**Comment by astone2014** [comment]
I was mistaken ignore my comments on first post.

I made a pull request with a workaround. Not sure if this is acceptable.
https://github.com/johannesjo/angular-material-css-vars/pull/36

I need to understand why that alpha is being set to 1 when it should be 0.38, or 0.5 in dark mode. It actually works in dark mode. Added test case to demo app so you can see what I mean.
