### ISSUE TITLE
Changing background & surface colours

### ISSUE THREAD

**Issue by zithith** [johannesjo/angular-material-css-vars#37]
Hey, not sure if this is a new feature you want to add, or just something I'm doing the wrong way but I want my app to have more than just 2 themes (dark & light) and some of them I'd like to set a custom background colour for.
This is fine using setVariable() when on a light theme, but if I use a dark theme then all the CSS rules get overriden by the dark-theme selector set which are more specific. I know that I could do something like this inside my style.css (or some theme sheet included therein):
```scss
&.dark-theme .background {
    background-color: <value>
}
```
But that still means that all themes that are set to "Dark" are using the same background colour, just not the material default of #202020. Do you have any suggestions?

I was looking at using a work around by having some themes set as light themes and using setVariable to update the background/card/dialog colours to be what I want them to, but this then means that your amazing auto-contrasting code doesn't evaluate it properly and I still get the dark text on the dark background.

Any help would be appreciated, I'd prefer a more programmatic solution than having to put in a bunch of CSS fixes/supporting sheets, etc; but just getting a better understanding of how to implement this would be great :)

**Comment by johannesjo** [comment]
Hey there! The background color is not really part of angular material so I didn't include anything here neither. 

You can simply use the body class for assigning a backgorund color. If you need more options then two I suggest to implement your own solution for now. I am open for changing it up, if more people need this though.
