### ISSUE TITLE
Mixins are not fully supported

### ISSUE THREAD

**Issue by Iworb** [johannesjo/angular-material-css-vars#38]
Hello there, I have a problem with mixins. I've checked extraction of primary color and it works well, but 'background' and 'foreground' properties are not.
Here's [an example](https://stackblitz.com/edit/angular-mat-css-vars). Text in the center should have 'card' background, but generated styles are invalid.
Generated: `.custom{background-color:var(--palette-background-card)}`
But `--palette-background-card` is `255,255,255` instead of `rgba(255,255,255)`.
In the default generated files this variable, like many others, called with rgba function: `background-color: rgba(var(--palette-background-card))`, but not in mixins.

In this case it's not fully supports ready theme mixins.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for opening this up. Im personally not using any custom theme mixins in my projects and I am very very busy with my other open source projects, but I gladly review and merge any PR someone comes up with.

**Comment by json-derulo** [comment]
With v5 there is now a standard version and a no-rgb version available, for example: `--palette-primary-50` and `--palette-primary-50-no-rgb`. It should not be necessary anymore to wrap the variables in `rgba()`.
