### ISSUE TITLE
Fallback

### ISSUE THREAD

**Issue by mhosman** [johannesjo/angular-material-css-vars#40]
Hi! I'm new with this library. I wan't to know how I can initialize a fallback or custom style by default, and give for example to the $mat-blue-grey, the value 900 as the selected primary color?

```
@import '../projects/material-css-vars/src/lib/public-util';
@import '../projects/material-css-vars/src/lib/main';

@include init-material-css-vars();

@include mat-css-set-palette-defaults($mat-blue-grey, 'primary');
@include mat-css-set-palette-defaults($mat-pink, 'accent');
@include mat-css-set-palette-defaults($mat-red, 'warn');

```

This idea is to get the same color when doing this with Material:

`$primary-color: mat-palette($mat-blue-grey, 900);`

**Comment by johannesjo** [comment]
[https://github.com/johannesjo/angular-material-css-vars#set-default-fallback-palettes](This) does not solve the issue for you?

**Comment by mhosman** [comment]
Yeah but how to set that number, example 900?

**Comment by johannesjo** [comment]
Why would you want to do that? As far as I understand it the the colors are intended to be a continuum from brighter to darker. You can of course just use the hex value of the palettes 900 as base color.
