### ISSUE TITLE
Is it possible to use a custom mat-dark-theme and mat-light-theme?

### ISSUE THREAD

**Issue by digimezzo** [johannesjo/angular-material-css-vars#42]
First of all, this project is amazing! Thank you.

I have a question. Is it possible to use a custom mat-dark-theme and mat-light-theme.
Before using your project, I was applying material colors the classic Angular way. Because the default Angular Material dark and light themes didn't fit my needs, I created my color themes using a custom mat-dark-theme and mat-light-theme, which had some colors slightly changed.

Can I, using this project, change the colors which are used in mat-dark-theme and mat-light-theme of plug in new dark and light themes?

Thank you.

**Comment by johannesjo** [comment]
Hi! This should be possible, but might be limited by the quirks of angular material. This library is not a replacement of angular material, but rather placed on top of it to make it work as well as possible with css variables. You can find a list of all accessible variables here: https://github.com/johannesjo/angular-material-css-vars/blob/master/projects/material-css-vars/src/lib/_variables.scss

Would be interesting to read how for you get with this approach. Maybe that's even something for an article on [dev.to](https://dev.to) if you're into those kind of things? :)

**Comment by johannesjo** [comment]
Btw. I just had a look at Knowte. Pretty slick UI. I am impressed! :)

**Comment by digimezzo** [comment]
Thanks for replying! Unfortunately, I could not get it to work. One of the colors that I need to set is MaterialCssVariables.BackgroundBackground. I've used the setVariable() function, but no luck. I've tried like this:

`setVariable(MaterialCssVariables.BackgroundBackground, '10, 10, 10')`

and

`setVariable(MaterialCssVariables.BackgroundBackground, '1a1a1a')`

**Comment by johannesjo** [comment]
> I'll try to write a blog post about it.

Cool keep me posted! :)
