### ISSUE TITLE
Material 10 is Considered Incompatible

### ISSUE THREAD

**Issue by astone2014** [johannesjo/angular-material-css-vars#43]
The message is pretty self explanatory. Let's check comparability and bump version or just don't limit version to 9.999.9.
`Package "angular-material-css-vars" has an incompatible peer dependency to "@angular/material" (requires ">=8.1.3 <=9.999.9", would install "10.0.0").`

**Comment by johannesjo** [comment]
Thanks for opening this up. Have you tested the lib with angular 10 yet?

**Comment by astone2014** [comment]
@johannesjo Works great so far on my application. Don't see any issues.

I went to go test the demo application.
```shell
git clone https://github.com/johannesjo/angular-material-css-vars.git
cd angular-material-css-vars
npm i
ng serve --open
```
I actually was getting errors.
```shell
ERROR in Failed to compile entry-point @angular/material/autocomplete (es2015 as esm2015) due to compilation errors:
node_modules/@angular/material/fesm2015/autocomplete.js:1466:26 - error NG1010: Value at position 0 in the NgModule.exports of MatAutocompleteModule is not a reference: [object Object]

1466                 exports: [
                              ~
1467                     CdkScrollableModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ...
1472                     MatCommonModule
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1473                 ],
     ~~~~~~~~~~~~~~~~~


    ERROR in projects/material-css-vars/src/lib/material-css-vars.service.ts:2:42 - error TS2307: Cannot find module '@ctrl/tinycolor'.

    2 import {Numberify, RGBA, TinyColor} from '@ctrl/tinycolor';
                                               ~~~~~~~~~~~~~~~~~
```

Part of it was me missing some dependencies (maybe consider adding these to sample application)
```shell
npm i @ctrl/tinycolor
```
Did some brief googling and found some bugs related to that autocomplete error.
Instead of try to figure that out I just updated everything.
```shell
ng update --all --force
```
Then the compile was good and the demo application started up.
At a glance going through application and playing with settings I don't see anything wrong.
![picture](https://i.imgur.com/cCPCra1.png)

**Comment by johannesjo** [comment]
I am closing this. Thank you and please let me know if you encounter any issues with this (I myself haven't made the switch to ng10 yet)...
