### ISSUE TITLE
Changing typography vars

### ISSUE THREAD

**Issue by toly-k** [johannesjo/angular-material-css-vars#45]
Is it possible to change mat-font-size, mat-font-family using the same principle? Is it something you guys would consider adding?

https://material.angular.io/guide/typography#material-typography-in-your-custom-css

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up!

I haven't looked into the code, but my basic rule of thumb for this is, that it should ideally work out of the box with new angular material releases and that – apart from replacing values with variables – all adjustments should be kept to an absolute minimum. This is a small project and meant to be a lightweight and simple to maintain extension for angular material, not a better version of it.

I also think that the feature should be optional as using CSS variables vs static values has a minor impact on rendering performance.

Personally I don't need this feature, but I gladly help out where I can if someone wants to work on this.
