### ISSUE TITLE
Disabled inputs are not graded out 

### ISSUE THREAD

**Issue by Wlada** [johannesjo/angular-material-css-vars#54]
## :ghost: Brief Description

Alpha variable is missing on disabled-text

## :pancakes: Action version

Disabled inputs are not graded out 

## Steps To Reproduce

Just disable some input fields

## :police_car: Expected behavior

Expecting to have graded out input field when is disabled

## :heavy_plus_sign: Additional context

I will create PR in order to fix this issue. please merge it when is possible. Thanks

**Comment by johannesjo** [comment]
Thank you very much for providing the fix!
Btw. updating the version in the package.json is not necessary. This is something I need to do separately.

**Comment by Wlada** [comment]
Your welcome. Thank you also for the great module. It helped us a lot. 
Will you publish this fixed version to npm repository?
Thanks again for quick response.

**Comment by johannesjo** [comment]
Yes. The release should be already out.
