### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by Daskus1** [johannesjo/angular-material-css-vars#56]
## Problem Statement

Currently it is not possible to render an application that uses `MaterialCssVarsService` on the server.

## Possible Solution

It should be possible to use `MaterialCssVarsService` in an SSR application, without the need to wrap the calls in a platform check call.
It seems like https://github.com/johannesjo/angular-material-css-vars/pull/39 would solve this issue. Is it planned to merge that PR? Otherwise, I could create a new PR for this issue.

**Comment by johannesjo** [comment]
Hey Daskus. Not in its current form at least. But maybe you can pick up on what is already there and check the proposed adjustments?

**Comment by Daskus1** [comment]
Ok nice, I'll create a new PR in the next days!
