### ISSUE TITLE
right use of materialCssVarsService.setVariable

### ISSUE THREAD

**Issue by doczoidberg** [johannesjo/angular-material-css-vars#6]
In my constructor I want to set the Background of a Dialog:

`  this.materialCssVarsService.setVariable(MaterialCssVariables.BackgroundDialog, '#AA222255');`

But now my Dialog is transparent. F12 gives me:

```
.mat-dialog-container {
    box-shadow: 0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0, 0, 0, 0.12);
    background: rgba(var(--palette-background-dialog), 1);
    color: rgba(var(--palette-foreground-text), var(--palette-foreground-text-alpha, 1));
}
```

Other functions works as it is in documentation described.

**Comment by johannesjo** [comment]
If you check with chrome dev tools under Elements/Styles and scroll down to `:root` you can see all of the variables. E.g. `--palette-background-dialog: 255, 255, 255;` which you can see is just three separate numbers representing rgb. It's this way, because this is how angular material works internally.

**Comment by doczoidberg** [comment]
color themes right but dialog background is transparent...

![image](https://user-images.githubusercontent.com/1972209/66383553-815da700-e9bd-11e9-90db-2cab9e375572.png)

**Comment by johannesjo** [comment]
Sorry I don't get your last comment.  Could you elaborate?

**Comment by doczoidberg** [comment]
I don't understand why my dialog background is transparent.

**Comment by johannesjo** [comment]
Did you read my comment above?

**Comment by doczoidberg** [comment]
ah sorry, I missed the last line. thank you! great work!
