### ISSUE TITLE
Set font-style && font-sizes similar to custom theme color using the library.

### ISSUE THREAD

**Issue by Nanda-albanero** [johannesjo/angular-material-css-vars#60]
Hi, 
* Do we have any option to apply the font-styles dynamically similar to apply theme color dynamically ?
```typescript 
       const hex = '#3f51b5';
       this.materialCssVarsService.setDarkTheme(true);
       this.materialCssVarsService.setPrimaryColor(hex);
       this.materialCssVarsService.setVariable(MaterialCssVariables.BackgroundCard,hex);
       this.materialCssVarsService.setAccentColor('#333');
```

**Comment by johannesjo** [comment]
Not yet. But if somebody wants to add it, I am all for it. Should be mostly straightforward to implement.

**Comment by Nanda-albanero** [comment]
> Not yet. But if somebody wants to add it, I am all for it. Should be mostly straightforward to implement.

Oh, that's a great news for me.
Can you please add the required changes?
I will be waiting for it.
Thanks.

**Comment by johannesjo** [comment]
I don't need the feature. So you would have to make a PR yourself I'm afraid.

**Comment by Nanda-albanero** [comment]
I've tried for it, couldn't get it to work. Can you share any sample
snippet that could help me?

**Comment by johannesjo** [comment]
I try to get back to you this weekend.

**Comment by Nanda-albanero** [comment]
Cool, thanks!

**Comment by johannesjo** [comment]
You should find all the relevant code here:
https://github.com/johannesjo/angular-material-css-vars/tree/master/projects/material-css-vars/src/lib

The relevant material part can be found here:
node_modules/@angular/material/_theming.scss

You would need to play around with passing css variables instead of values to `mat-typography-config` like so:
``` 
$custom-typography: mat-typography-config(
  $font-family: var(--custom-font-family),
);
@include init-material-css-vars($typography-config: $custom-typography); 
```

**Comment by Nanda-albanero** [comment]
Thanks, I'll check it out.

**Comment by muellerdberlin** [comment]
Same problem for me. I will try to find a solution for this. What I also need is a custom font selector (for different type of users) without loading a bulk of fonts for every user... it's always just one font needed.
Let's keep in touch.

**Comment by json-derulo** [comment]
The solution is now fully described in the docs, so I'm closing this issue.

@muellerdberlin In Angular Material typography, it's not possible to provide paths to fonts (see the [typography docs](https://material.angular.io/guide/typography)), so I don't see your feature request in the scope of this package. You should find a custom solution for this.
