### ISSUE TITLE
Angular 11 is considered incompatible

### ISSUE THREAD

**Issue by Akkora** [johannesjo/angular-material-css-vars#61]
Currently the peer dependencies are defined as followed.

```
"peerDependencies": {
    "@angular/common": ">=8.1.3 <=10.999.9",
    "@angular/core": ">=8.1.3 <=10.999.9",
    "@angular/material": ">=8.1.3 <=10.999.9"
},
```

If you are using current version of angular and angular material, this leads to the error message `Package "angular-material-css-vars" has an incompatible peer dependency to "@angular/material" (requires ">=8.1.3 <=10.999.9", would install "11.1.0").`

We are using angular and angular material in version 11.1.0 and have no problems with the angular-material-css-vars package. Therefore it should be updated to support angular 11 😀

**Comment by johannesjo** [comment]
Thank you very much for letting me now! I provide an update soon.
