### ISSUE TITLE
Drawer background color variable

### ISSUE THREAD

**Issue by definitely-unique-username** [johannesjo/angular-material-css-vars#62]
## :ghost: Brief Description

The same variable is used for card background and drawer backdrop: `--palette-background-card`. 
Changing this variable also leads to changing drawer bg color (see `.mat-drawer-backdrop` class)

## Steps To Reproduce

1. Add mat-card and mat-sidenav components
2. Open drawer
3. Change `--palette-background-card` variable
4.  Observe card and drawer bg

## :police_car: Expected behavior
Drawer bg color should not change

**Comment by johannesjo** [comment]
Thanks for opening this up. This is less of a bug than an improve I'd say :) 

Though I personally don't need this adjustment, a PR would be welcome.

**Comment by json-derulo** [comment]
In v5, the variables for foreground and background colors have been removed from the package. The discussion on whether this feature will be added back and if yes how is tracked in #116. Your feature request will be considered there as well.
