### ISSUE TITLE
v2 - variables.scss not usable with the old SASS module system

### ISSUE THREAD

**Issue by dsimon-onventis** [johannesjo/angular-material-css-vars#73]
I'm using angular-material-css-vars in a project, where I'm not able to use the new SASS module system (`@use` rule). Since v2 of this library, I cannot import `variables.scss` anymore, because it's first line is the following:

```
@use '~@angular/material'as mat;
```

Is it possible to revert this change and switch back to the old SASS module system?

**Comment by johannesjo** [comment]
Hi there. Unfortunately not, as angular material now uses the new system and unless they switch back to the old module system, there is no way to do it. You can however stay with v1.2 of this lib and 11.x of angular material.
