### ISSUE TITLE
setVariable doesn't do anything.

### ISSUE THREAD

**Issue by pham93** [johannesjo/angular-material-css-vars#74]
```
this.materialCssVarsService(MaterialCssVariables.BackgroundAppBar, 'green');
```
this doesn't work anymore in Angular v.12

 'BackgroundStatusBar' = '--palette-background-status-bar',
  'BackgroundAppBar' = '--palette-background-app-bar',
  'BackgroundBackground' = '--palette-background-background',
  'BackgroundHover' = '--palette-background-hover',
  'BackgroundHoverAlpha' = '--palette-background-hover-alpha',
  'BackgroundCard' = '--palette-background-card',
  'BackgroundDialog' = '--palette-background-dialog',
  'BackgroundDisabledButton' = '--palette-background-disabled-button',
  'BackgroundDisabledButtonAlpha' = '--palette-background-disabled-button-alpha',
  'BackgroundRaisedButton' = '--palette-background-raised-button',
  'BackgroundFocusedButton' = '--palette-background-focused-button',
  'BackgroundSelectedButton' = '--palette-background-selected-button',
  'BackgroundSelectedDisabledButton' = '--palette-background-selected-disabled-button',
  'BackgroundDisabledButtonToggle' = '--palette-background-disabled-button-toggle',
  'BackgroundUnselectedChip' = '--palette-background-unselected-chip',
  'BackgroundDisabledListOption' = '--palette-background-disabled-list-option',

**Comment by johannesjo** [comment]
Thanks for opening this up! Personally I am still staying with v11 as v12 introduces so many issues and with v13 everything might be completely different again, as they're working on some other big changes under the hub.

This being said, I am happy to accept any PR dealing with this.

**Comment by pedrojrivera** [comment]
@pham93 I had removed that logic when solving the v12 issue. I needed to reverse engineer a few things. I am in the process of adding the logic back in so that variables the foreground and background variables can be manipulated.  The old logic will not work due to Angular v12 changes. But I do have a solution.

**Comment by pedrojrivera** [comment]
@johannesjo Added a new pull request that should fix the setVariable() feature.  https://github.com/johannesjo/angular-material-css-vars/pull/75

**Comment by johannesjo** [comment]
Thank you very much once more @pedrojrivera ! Seems to work nicely. I made  a new release with the changes.

**Comment by pham93** [comment]
setVariable() works now. Thank you!
