### ISSUE TITLE
Color of mat-snack-bar not resolved correctly in dark mode

### ISSUE THREAD

**Issue by dtslvr** [johannesjo/angular-material-css-vars#76]
### :speaking_head: Foreword

The text of a snack bar is not visible in dark mode, because it is not resolved correctly.

## :ghost: Brief Description

The CSS is as follows
```
.is-dark-theme .mat-snack-bar-container {
  color: 0, 0, 0, 0.87;
}  
```

instead of

```
.is-dark-theme .mat-snack-bar-container {
  color: rgba(0, 0, 0, 0.87)
}
```

## :pancakes: Action version

angular-material-css-vars: 2.1.0

## :police_car: Expected behavior

The text of the snack bar is displayed in dark color (in dark mode).

**Comment by johannesjo** [comment]
Thanks for reporting this. Would you mind providing a PR to fix this?

**Comment by pedrojrivera** [comment]
I created a new pull reguest https://github.com/johannesjo/angular-material-css-vars/pull/77 that fixes this issue.

**Comment by dtslvr** [comment]
> I created a new PR #77 that fixes this issue.

Great @pedrojrivera! 👍🏻 
I will integrate and test it in https://github.com/ghostfolio/ghostfolio as soon as it is published.

**Comment by dtslvr** [comment]
#77 has been merged for a long time and I have not received a notification 😏 

I can confirm that this issue has been fixed. Thanks for your efforts @pedrojrivera!
