### ISSUE TITLE
Repeated var instead of alpha var breaks disabled buttons

### ISSUE THREAD

**Issue by dstalor** [johannesjo/angular-material-css-vars#78]
It looks like the variable name was repeated instead of using the alpha variable for foreground disabled buttons.

https://github.com/johannesjo/angular-material-css-vars/blob/6149449a7199c497656245efffc4e8df302ab3b4/projects/material-css-vars/src/lib/_variables.scss#L378 https://github.com/johannesjo/angular-material-css-vars/blob/6149449a7199c497656245efffc4e8df302ab3b4/projects/material-css-vars/src/lib/_variables.scss#L397

This results in compiled code like this:
```css
    color: rgba(0, 0, 0, 0, 0, 0);
    color: rgba(var(--palette-foreground-disabled-button), var(--palette-foreground-disabled-button));
```

**Comment by pedrojrivera** [comment]
@dstalor I fixed the program in this PR https://github.com/johannesjo/angular-material-css-vars/pull/79. Thanks!

**Comment by johannesjo** [comment]
Thank you once more @pedrojrivera !
