### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by aigens** [johannesjo/angular-material-css-vars#87]
After upgrade ng material to 13, material css vars failed to compile. The issue seems related to how angular css is imported without "~".

**Comment by stvno** [comment]
I managed to get around it by referencing directly to the scss file, eg. 
`@import '~angular-material-css-vars/src/lib/_main.scss';`

So I guess it has to do with the way the scss files are exposed in the module

**Comment by johannesjo** [comment]
Yes, I am sorry. This is something that slipped in with the latest release. Unfortunately I doesn't make much sense anymore to provide a fix for this, since this in turn will require people who used  @stvno  solution to adjust their code. Not ideal, I know...

**Comment by aigens** [comment]
It seems to work after these changes:

Change from:
@use '~@angular/material'as mat;

to:
@use '@angular/material'as mat;

in the _main.scss and _variables.scss files.

Maybe can adjust these 2 files for version that support NG13+?

**Comment by aigens** [comment]
It seems this commit on master fix it:

https://github.com/johannesjo/angular-material-css-vars/commit/d948c029155c95ee3e1b42b2bd0e737d67979317

Possible to release version base on this?

**Comment by johannesjo** [comment]
> Possible to release version base on this?

It's already released as v3.0.0

**Comment by aigens** [comment]
Ok. Upgrading to 3.0.0 and import like this seems working:

//@import "~angular-material-css-vars/main";
@import '~angular-material-css-vars/src/lib/_main.scss';

Thanks!
