### ISSUE TITLE
@mixin init-css-vars

### ISSUE THREAD

**Issue by hollowb4ck** [johannesjo/angular-material-css-vars#91]
Why did you remove initialization for $default-theme?

```
@include _mat-css-root($default-theme);
```

https://github.com/johannesjo/angular-material-css-vars/blob/20940b30bbd5a7bf54d55ded00e2f2a457923ab5/projects/material-css-vars/src/lib/_main.scss#L12

**Comment by json-derulo** [comment]
The current state of the code contains initialization of the `$default-theme`, probably it was just a leftover.
